/**
 * What is new: the changelog inside the add-on, and the card that offers it.
 *
 * The words come from the changelogs themselves - `CHANGELOG.md` and
 * `CHANGELOG.ru.md` - by way of `tools/build-changelog.js`, which reads them
 * into `src/changelog-data.js`. One source and one generated copy, so what
 * this guards is the copy still being the source, and the window drawing what
 * is in it.
 *
 * What can quietly go wrong here:
 *
 *   - a changelog is edited and the tool is never run, so the add-on goes on
 *     announcing the release before last. Nothing breaks; it is simply out of
 *     date, in the one window somebody opened to find out what had changed.
 *   - a translation falls a release behind, and a version ships with nothing
 *     under it, or with the wrong lines under the wrong heading.
 *   - the unreleased section is picked up, which announces a version nobody
 *     has.
 *   - a line uses markdown the window cannot draw, so the asterisks and
 *     brackets are read out on screen exactly as they were typed.
 *   - the card comes back after it has been answered, which makes it a thing
 *     that cannot be put down; or it is shown to somebody who has just
 *     installed the add-on, who has nothing to catch up on; or it is *not*
 *     shown to everybody who was already here before the marker existed, who
 *     are exactly who it is for.
 *   - the marker moves into `settings`, where "Reset all settings" wipes it
 *     and the same release is announced all over again.
 *   - the window is written before the settings window, so opening it from the
 *     About page opens it behind - which looks like nothing happening at all.
 *   - Escape reaches the settings window rather than the changelog standing on
 *     top of it, the way it already has to for the archive sheet.
 *
 *   node test/changelog.test.js [path/to/src]
 */
const fs = require('fs');
const vm = require('vm');
const path = require('path');

const { El, document } = require('./dom-shim');

const ROOT = path.join(__dirname, '..');
const SRC = process.argv[2] || path.join(ROOT, 'src');
/* Line endings normalised, the way every other suite here normalises them: the
   markers below are written with plain newlines and would match nothing on a
   CRLF checkout. */
const read = file => fs.readFileSync(path.join(SRC, file), 'utf8').replace(/\r\n/g, '\n');
const readRoot = file => fs.readFileSync(path.join(ROOT, file), 'utf8').replace(/\r\n/g, '\n');

const js = read('newtab.js');
const html = read('newtab.html');
const css = read('newtab.css');

const tool = require(path.join(ROOT, 'tools', 'build-changelog.js'));

const results = [];
const check = (name, pass, detail = '') => results.push({ name, pass, detail });

// ------------------------------------------------------------------ sandbox

/**
 * The add-on's own modules, with the browser telling them `lang` is the
 * interface language - which is the one thing that decides which changelog is
 * drawn. A context per language, because the module reads it once as it loads,
 * exactly as it does in a page.
 */
function load(lang) {
  const sandbox = { document, console };
  if (lang) {
    sandbox.browser = { i18n: { getUILanguage: () => lang, getMessage: () => '' } };
  }
  vm.createContext(sandbox);
  ['i18n.js', 'changelog-data.js', 'changelog.js'].forEach(file => {
    vm.runInContext(read(file), sandbox, { filename: file });
  });
  return vm.runInContext('Changelog', sandbox);
}

const Changelog = load(null);

// --------------------------------------------- the copy against the source

/* The whole point of generating it: what is in `src/` has to be what the tool
   would write today, or the add-on is telling people about an older release
   than the one they can read about on the project page. */
const wanted = tool.generate(tool.build()).replace(/\r\n/g, '\n');
check('the generated data is what the changelogs say today',
  read('changelog-data.js') === wanted,
  'if this fails, run: node tools/build-changelog.js');

check('and it says on its face that it is generated, so nobody edits it by hand',
  read('changelog-data.js').includes('GENERATED by tools/build-changelog.js'));

const documents = tool.documents();
check('the changelog is written in more than one language',
  documents.length > 1, documents.map(doc => doc.lang + ' (' + doc.name + ')').join(', '));

check('English is the one every other is read against',
  documents[0].lang === 'en' && documents[0].name === 'CHANGELOG.md');

/* The tool refuses a translation that has fallen behind rather than shipping
   half of one. Asked here too, because it is the failure a release would
   otherwise walk straight into. */
const shapes = Object.entries(tool.build())
  .map(([lang, releases]) => [lang, tool.shapeOf(releases)]);
check('every language tells the same story',
  shapes.every(([, shape]) => shape === shapes[0][1]),
  shapes.map(([lang, shape]) => lang + ': ' + shape).join('  |  '));

// ------------------------------------------------- and what it leaves out

const CHANGELOG = readRoot('CHANGELOG.md');
const versions = Changelog.DATA.en.map(release => release.version);

/* Where a changelog parks work under an Unreleased heading, it stays out of
   the add-on: it is not a version anybody is running, and saying what is in it
   would be telling people about something they do not have. Where a release is
   written up under its own number straight away, there is nothing to leave
   out - and the check costs nothing either way. */
check('nothing unreleased is announced',
  !versions.includes('Unreleased'), versions.join(', '));

check('every released version is there', versions.length > 0, versions.join(', '));

const manifest = JSON.parse(readRoot('manifest.json'));
check('and the newest is the version the add-on actually is',
  Changelog.latest() === manifest.version,
  Changelog.latest() + ' vs manifest ' + manifest.version);

/* Only bold and code are read back out of a line. Anything else markdown can
   do would be read out on screen as typed. */
const unsupported = Changelog.DATA.en
  .flatMap(release => release.groups.flatMap(group => group.lines))
  .filter(line => /\]\(|^#|!\[|<[a-z]/i.test(line));
check('no line uses markdown the window cannot draw',
  unsupported.length === 0, unsupported.join(' | '));

// ------------------------------------------------------ the reader's own

const english = load('en-GB');
const russian = load('ru-RU');
const greek = load('el');

check('a Russian browser is given the Russian changelog',
  russian.language() === 'ru', russian.language());

check('an English one, the English', english.language() === 'en', english.language());

check('and a language nothing is written in falls back to English',
  greek.language() === 'en', greek.language());

check('the two say different things, which is the whole point',
  russian.releases()[0].groups[0].lines[0] !== english.releases()[0].groups[0].lines[0],
  russian.releases()[0].groups[0].lines[0]);

check('a page opened straight off disk, with no browser to ask, gets English',
  Changelog.language() === 'en');

// ----------------------------------------------------------- the drawing

const root = new El('div');
russian.render(root);

const drawn = root.findAll(el => el.className === 'changelog__version');
check('the window draws a block per release', drawn.length === versions.length,
  drawn.map(el => el.textContent).join(' | '));

const lines = () => root.findAll(el => el.className === 'changelog__line');
const total = Changelog.DATA.en
  .reduce((n, release) => n + release.groups.reduce((m, g) => m + g.lines.length, 0), 0);

check('and every line of every release under it', lines().length === total,
  lines().length + ' of ' + total);

check('in the language the reader browses in, not in English',
  lines().some(el => /[Ѐ-ӿ]/.test(el.textContent)),
  lines().map(el => el.textContent).join(' | '));

/* The About page raises the same window a second time, and a list that
   appended rather than replaced would say everything twice. */
russian.render(root);
check('opening it twice does not draw it twice', lines().length === total,
  lines().length + ' of ' + total);

// -- and the little markup the changelogs actually use

const bolded = new El('div');
Changelog.inline('the new **Archive** section').forEach(node => bolded.append(node));
check('a bold run comes through as bold, not as asterisks',
  bolded.textContent === 'the new Archive section'
    && bolded.findAll(el => el.tagName === 'strong').length === 1,
  bolded.textContent);

const coded = new El('div');
Changelog.inline('the `.xpi` on a release').forEach(node => coded.append(node));
check('and a code run as code',
  coded.textContent === 'the .xpi on a release'
    && coded.findAll(el => el.tagName === 'code').length === 1,
  coded.textContent);

const plain = new El('div');
Changelog.inline('nothing marked up at all').forEach(node => plain.append(node));
check('a line with no markup in it is left alone',
  plain.textContent === 'nothing marked up at all', plain.textContent);

// ------------------------------------------------------------- the offer

/**
 * `offerChangelog` and `closeNotice`, lifted out of newtab.js and run against
 * stubs. The rules they carry are the whole of what makes the card bearable,
 * and they are few enough lines to get subtly wrong without noticing.
 */
function offerWith(seen, version, usedBefore) {
  const from = js.indexOf('  async function offerChangelog(');
  const to = js.indexOf('  btnNoticeLater.addEventListener');
  if (from < 0 || to < 0) throw new Error('offerChangelog has moved out from under this test');

  const saved = [];
  const notice = { hidden: true };
  const body = { textContent: '' };
  const stubs = {
    Changelog: { latest: () => version },
    Store: {
      loadChangelogSeen: () => Promise.resolve(seen),
      saveChangelogSeen: written => saved.push(written)
    },
    updateNotice: notice,
    noticeBody: body,
    t: (key, sub) => key + ':' + sub,
    openDialog: () => {},
    changelogModal: {},
    changelogBody: new El('div')
  };

  const source = js.slice(from, to) + '\nreturn { offerChangelog, closeNotice };';
  const made = new Function(...Object.keys(stubs), source)(...Object.values(stubs));
  return Object.assign(made, {
    saved, notice, body,
    offer: () => made.offerChangelog(usedBefore)
  });
}

(async () => {
  const fresh = offerWith('', '1.2.0', false);
  await fresh.offer();
  check('somebody who has just installed it is told nothing',
    fresh.notice.hidden === true, 'shown: ' + !fresh.notice.hidden);
  check('but the version is written down, so the next release does speak',
    fresh.saved.join(',') === '1.2.0', fresh.saved.join(','));

  /* Everybody already using the add-on when this ships has no marker either,
     and they are exactly who the card is for. Told apart by whether the
     profile held anything at all. */
  const carriedOver = offerWith('', '1.2.0', true);
  await carriedOver.offer();
  check('somebody who was already here, from before there was a marker, is told',
    carriedOver.notice.hidden === false, 'shown: ' + !carriedOver.notice.hidden);
  check('and nothing is written down until they answer',
    carriedOver.saved.length === 0, carriedOver.saved.join(','));

  const same = offerWith('1.2.0', '1.2.0', true);
  await same.offer();
  check('a version already offered is not offered again',
    same.notice.hidden === true && same.saved.length === 0,
    'shown: ' + !same.notice.hidden + ', wrote: ' + same.saved.join(','));

  const updated = offerWith('1.1.0', '1.2.0', true);
  await updated.offer();
  check('an update is offered', updated.notice.hidden === false,
    'shown: ' + !updated.notice.hidden);
  check('and the card names the version it is about',
    updated.body.textContent.includes('1.2.0'), updated.body.textContent);
  check('nothing is written down until it has been answered',
    updated.saved.length === 0, updated.saved.join(','));

  updated.closeNotice();
  check('Later is an answer rather than a postponement: it counts as offered',
    updated.notice.hidden === true && updated.saved.join(',') === '1.2.0',
    updated.saved.join(','));

  report();
})();

function report() {

// ------------------------------------------------------- and where it lives

/* Every dialog here carries the same z-index, so what stands in front is
   whatever is written last. The About page opens this one from inside the
   settings window, so written before it, it opens behind it - which looks like
   nothing happening at all. */
const order = ['settings', 'changelog', 'confirmAlert']
  .map(id => html.indexOf('id="' + id + '"'));
check('the window is written after the one that opens it, so it stands in front',
  order[0] > -1 && order[1] > order[0],
  'settings at ' + order[0] + ', changelog at ' + order[1]);

check('and still behind the alert, which stands over everything',
  order[2] > order[1], 'alert at ' + order[2]);

/* The card is not a dialog, so it must not float over one: above the scrim it
   would be the one lit thing on a dimmed page, and inert with it. */
const zOf = rule => {
  const at = css.indexOf(rule);
  // parseInt rather than a pattern: it skips the space after the colon and
  // stops at the semicolon on its own.
  return at < 0 ? null : parseInt(css.slice(at, at + 400).split('z-index:')[1], 10);
};
const NEWLINE = String.fromCharCode(10);
const noticeZ = zOf(NEWLINE + '.notice {');
const modalZ = zOf(NEWLINE + '.modal {');
check('the card sits under the dialogs rather than over their scrim',
  noticeZ < modalZ, '.notice ' + noticeZ + ' vs .modal ' + modalZ);

const noticeRule = css.slice(css.indexOf(NEWLINE + '.notice {'),
                       css.indexOf('.notice[hidden]'));
check('the strip the card is centred in lets clicks through to the page',
  noticeRule.includes('pointer-events: none')
    && css.slice(css.indexOf('.notice__box {'), css.indexOf('@keyframes notice-in'))
      .includes('pointer-events: auto'),
  'none on the strip, auto on the card');

check('the card is not a dialog: it dims nothing and takes no focus',
  html.includes('<aside class="notice"') && html.includes('role="status"')
    && !/id="updateNotice"[^>]*role="dialog"/.test(html));

check('both of its buttons answer it',
  js.includes('btnNoticeLater.addEventListener')
    && js.includes('btnNoticeOpen.addEventListener')
    && (js.match(/closeNotice\(\)/g) || []).length >= 2);

/* The marker is page state, not a preference. Kept in `settings` it would be
   wiped by "Reset all settings", and the release announced a second time. */
check('what has been seen is its own storage key, not a setting',
  read('storage.js').includes("const CHANGELOG_SEEN = 'changelogSeen';")
    && !read('schema.js').includes('changelogSeen'));

check('and a tab that reads it says so to the others',
  read('storage.js').includes('[CHANGELOG_SEEN,'));

check('the window is opened from the About page as well as from the card',
  read('schema.js').includes("key: 'changelog',")
    && js.includes("if (key === 'changelog') return openChangelog();"));

/* It opens over the settings window when the About page raises it, so Escape
   has to reach it first - the same rule the archive sheet already needs. */
const escape = js.slice(js.indexOf('if (!isCancelKey(e)) return;'),
                        js.indexOf('else closeSearch();'));
check('Escape reaches it before the window it is standing on',
  escape.includes('changelogModal')
    && escape.indexOf('changelogModal') < escape.indexOf('settingsModal'),
  escape.split('\n').filter(line => line.includes('Modal')).map(l => l.trim()).join(' '));

check('and it is offered only once the page itself is up',
  js.indexOf('offerChangelog(usedBefore);')
    > js.indexOf("document.body.classList.remove('is-loading')"));

/* It answers "was there anything in storage?", so it has to be read before the
   page puts anything there - in the same breath as everything else boot loads,
   not where it is used. */
check('and what it is asked is read before the page writes anything',
  js.indexOf('Store.usedBefore()') < js.indexOf("classList.remove('is-loading')"),
  'read at boot');

check('the generated data is loaded before the module that draws it',
  html.indexOf('changelog-data.js') > -1
    && html.indexOf('changelog-data.js') < html.indexOf('src="changelog.js"'));

// ------------------------------------------------------------------ report

let failed = 0;
results.forEach(({ name, pass, detail }) => {
  if (!pass) failed++;
  console.log((pass ? 'PASS  ' : 'FAIL  ') + name + (detail ? '  (' + detail + ')' : ''));
});
console.log('\n' + (results.length - failed) + '/' + results.length + ' passed');
process.exit(failed ? 1 : 0);
}
