/**
 * Every released version, in every language the changelog is written in.
 *
 * GENERATED by tools/build-changelog.js from CHANGELOG.md and its
 * translations. Do not edit it: edit the changelogs and run the tool.
 *
 * `src/changelog.js` picks the reader's language out of this and draws it.
 */
const CHANGELOG_DATA = {
  "en": [
    {
      "version": "1.1.0",
      "groups": [
        {
          "kind": "New features",
          "lines": [
            "**Bookmark archive.** A \"Move to archive\" item has been added to the tile context menu, which lets you put a bookmark away for a while without deleting it outright. Archived tiles live in a section of the settings of their own, from which they can be restored or deleted for good.",
            "**Bookmark search.** A search button has been added to the start page, opening a search field that filters bookmarks by name and by address. Search can also be opened from the context menu, and the button can be hidden.",
            "**Names shown per tile.** A setting of its own has been added to the tile editor, which hides or shows the name of the edited bookmark only. A \"Reset the names set on single tiles\" option has been added to the settings, which puts every tile back to the shared name setting.",
            "**Reading the changelog.** After the add-on updates you are now offered a look at what has changed. Dismissing that takes the notice away until the next update, and the changelog can be opened from the \"About\" section of the settings.",
            "**The add-on's icon in the tab.** An option has been added to the settings that turns on the OpenTiles logo in the new tab."
          ]
        },
        {
          "kind": "UI/UX improvements and bug fixes",
          "lines": [
            "Animations have been added for deleting and archiving tiles.",
            "The add-on can now be installed from the project page on GitHub as well as from the Mozilla add-on store. To do that, download the `.xpi` file from the release page.",
            "Fixed a bug where the background of a tile with a transparent background froze while the tile was being moved, instead of changing as it went.",
            "In the \"About\" section of the settings the add-on's icon is now always shown in its light variant, whatever theme is set."
          ]
        }
      ]
    },
    {
      "version": "1.0.0",
      "groups": [
        {
          "kind": null,
          "lines": [
            "First release."
          ]
        }
      ]
    }
  ],
  "ru": [
    {
      "version": "1.1.0",
      "groups": [
        {
          "kind": "Новые возможности",
          "lines": [
            "**Архив закладок.** В контекстное меню плиток добавлен пункт \"Переместить в архив\", который позволять временно убрать закладку, не удаляя её полностью. Архивированные плитки находятся в соответствующем разделе настроек, из которого их можно удалить окончательно или восстановить.",
            "**Поиск по закладкам** На главный экран добавлена кнопка поиска, открывающая поисковую строку, которая фильтрует закладки по названию и по адресу. Открывать поиск можно из контекстного меню, а кнопку можно скрыть.",
            "**Индивидуальное отображение названия для плиток.** В редактор плиток добавлена индивидуальная настройка, которая позволяет скрывать или показывать название только для редактируемой закладки. В настройки добавлена опция \"Сброс индивидуальных настроек названий плиток\", которая позволяет вернуть все плитки к общей настройке отображения названий.",
            "**Просмотр списка изменений.** Теперь после обновления плагина будет предложено посмотреть список изменений. Скрытие убирает уведомление до следующего обновления, а список изменений можно отркыть из раздела настроек \"О плагине\".",
            "**Логотип плагина во вкладке.** В настройки добавлена опция, которая включает отображение логотипа OpenTiles в новой вкладке."
          ]
        },
        {
          "kind": "UI/UX улучшения и исправления багов",
          "lines": [
            "Добавлены анимации удаления и архивирования плиток.",
            "Теперь расширение можно установить со страницы проекта на GitHub, а не только из магазина расширений Mozilla. Для этого скачайте файл `.xpi` со страницы релиза.",
            "Исправлен баг, из-за которого при перемещении плитки с прозрачным фоном, её фон застывал, а не динамически менялся.",
            "В разделе настроек \"О плагине\" значок плагина теперь всегда показывается в светлом варианте, независимо от выбранной темы."
          ]
        }
      ]
    },
    {
      "version": "1.0.0",
      "groups": [
        {
          "kind": null,
          "lines": [
            "Первый релиз."
          ]
        }
      ]
    }
  ]
};

/* Read by the tests, which run this file under `node`. Harmless in the
   browser, where there is no `module`. */
if (typeof module !== 'undefined') module.exports = CHANGELOG_DATA;
